#!/usr/bin/env python3

import sys
import logging
from pathlib import Path

from core import (
    ConversionReport,
    ServiceRegistry,
    HLASMParser,
    DataDivisionPlugin,
    DirectivePlugin,
    DummyMLConverter,
    HuggingFaceMLConverter,
    Orchestrator,
    ConfigurationManager,
    ReportGenerator,
    ConversionContext # Import ConversionContext
)

# Import individual instruction handler modules
from plugins.instruction import (
    arithmetic, boolean, branch, compare, decimal, fallback, load_store, move, shift,
    loop_control, # Our new plugin
    decimal_packed, # Our new plugin
)

from plugins.instruction.register_mapping import run_register_mapping_pre_pass


_log = logging.getLogger(__name__)

def setup_services():
    """Wire up the IoC container with default implementations."""
    # 1. Config
    cfg_mgr = ConfigurationManager().load()
    cfg = cfg_mgr.config

    # 2. Parser
    ServiceRegistry.register("parser", HLASMParser())

    # 3. Plugins
    # Create a dummy context for initialization. The real context is passed during _convert.
    dummy_context = ConversionContext() 

    instruction_handlers = [
        # Order can matter for priority. General handlers first, then specific.
        # DirectivePlugin and DataDivisionPlugin manage specific divisions, so their order might be important
        DirectivePlugin(dummy_context), # Pass dummy context
        DataDivisionPlugin(dummy_context), # Pass dummy context
        
        # Our new plugins
        loop_control.LoopControlPlugin(dummy_context), # Pass dummy context
        decimal_packed.DecimalPackedPlugin(dummy_context), # Pass dummy context

        # Existing instruction handlers (ensure they conform to IInstructionHandler)
        arithmetic.ArithmeticHandler(dummy_context),
        boolean.BooleanHandler(dummy_context),
        branch.BranchHandler(dummy_context),
        compare.CompareHandler(dummy_context),
        decimal.DecimalHandler(dummy_context),
        load_store.LoadStoreHandler(dummy_context),
        move.MoveHandler(dummy_context),
        shift.ShiftHandler(dummy_context),
        fallback.FallbackHandler(dummy_context), # Should be last as a general fallback
    ]

    # Register all instruction handlers directly. The Orchestrator will manage them.
    ServiceRegistry.register("plugins", instruction_handlers)

    # 4. ML Bridge
    if cfg.enable_ml:
        opts = {
            "ml_model_name":     cfg.ml_model_name,
            "ml_quantization":   cfg.ml_quantization,
            "ml_max_memory_gb":  cfg.ml_max_memory_gb,
            "ml_cache_dir":      cfg.ml_cache_dir,
            "ml_device":         cfg.ml_device,
            "min_ml_confidence": cfg.min_ml_confidence,
        }
        try:
            ServiceRegistry.register("ml_converter", HuggingFaceMLConverter(opts))
        except Exception as e:
            _log.warning("Failed to initialize ML converter, falling back to dummy: %s", e)
            ServiceRegistry.register("ml_converter", DummyMLConverter())
    else:
        ServiceRegistry.register("ml_converter", DummyMLConverter())

def main():
    if len(sys.argv) < 2:
        print("Usage: python main.py <source_file.asm>")
        sys.exit(1)

    source_file = sys.argv[1]

    logging.basicConfig(level=logging.INFO)

    setup_services()

    orch = Orchestrator()
    try:
        # First, parse the file to get all statements for the pre-pass
        parser = ServiceRegistry.get("parser") # Corrected get_service to get
        source_content = Path(source_file).read_text()
        all_statements = parser.parse(source_content)

        # Create an initial context and run the register mapping pre-pass
        context = ConversionContext() 
        run_register_mapping_pre_pass(context, all_statements)

        # Now, pass the context and statements to the orchestrator for the main conversion
        report = orch.convert_source(source_content, source_path=source_file, initial_context=context)

        print(f"""
Conversion Report for {source_file}
""") # Corrected f-string
        print("-" * 40)
        print(f"Total statements: {report.total_lines}")
        print(f"Duration:         {report.duration_ms:.2f} ms")
        print(f"Success rate:     {report.success_rate * 100:.1f}%")

        output_file = Path(source_file).with_suffix(".cbl")
        
        # The _assemble_cobol method in Orchestrator should now handle all divisions
        # including the WORKING-STORAGE generated by RegisterMappingPlugin.
        # So, we just write the report.cobol_text directly.
        output_file.write_text(report.cobol_text)
        print(f"""
COBOL source written to: {output_file}
""")

        # JSON report
        json_report = ReportGenerator.generate(report)
        json_file = Path(source_file).with_suffix(".json")
        json_file.write_text(json_report)
        print(f"Review report written to: {json_file}")

    except Exception as e:
        _log.exception("An error occurred during conversion.")
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
